name: Build and Deploy Backend

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to self-hosted server
    needs: build-and-push
    runs-on: [self-hosted, polaris]
    steps:
      - name: Login to GHCR
        run: echo $GHCR_TOKEN | docker login ghcr.io -u abdulkadirerdem --password-stdin
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Pull latest image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Restart backend container
        working-directory: /opt/apps/backend
        run: docker compose up -d

      - name: Cleanup old images
        run: docker image prune -af
